name: Test
on:
  workflow_dispatch:
    inputs:
      allbuild:
        description: '构建全部'
        required: false
        type: boolean
        default: false
      desktop:
        description: '构建桌面版本'
        required: false
        type: boolean
        default: false
      android:
        description: '构建安卓版本'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ==================== 环境依赖安装 ====================
      - name: Check and Use System Go
        run: |
          go version
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Checkout Source Code
        run: |
          git clone https://github.com/SagerNet/sing-box sing-box
          git clone https://github.com/SagerNet/sing-box-for-android sing-box-for-android

      - name: sing-box Extra Modify
        run: |
          echo '修改VersionName'
          openssl des3 -md sha256 -d -k ${{ secrets.TAR_PASS }} -salt -in extra_v2.tar.gz | tar -xzvf -
          sh modify.sh

      # ==================== 桌面版构建与上传 ====================
      - name: Build Desktop
        if: github.event.inputs.allbuild == 'true' || github.event.inputs.desktop == 'true'
        working-directory: sing-box
        run: |-
          go mod tidy
          make

      - name: Upload Desktop Artifact (exe)
        if: (github.event.inputs.allbuild == 'true' || github.event.inputs.desktop == 'true') && github.event.name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box.exe
          path: sing-box/sing-box.exe

      - name: Upload Desktop Artifact (aarch64)
        if: (github.event.inputs.allbuild == 'true' || github.event.inputs.desktop == 'true') && github.event.name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_aarch64
          path: sing-box/sing-box_aarch64

      - name: Upload Desktop Artifact (x86_64)
        if: (github.event.inputs.allbuild == 'true' || github.event.inputs.desktop == 'true') && github.event.name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_x86_64
          path: sing-box/sing-box_x86_64

      - name: Upload Desktop Artifact (freebsd)
        if: (github.event.inputs.allbuild == 'true' || github.event.inputs.desktop == 'true') && github.event.name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_freebsd_x86_64
          path: sing-box/sing-box_freebsdx86_64

      # ==================== 安卓前置修改 ====================
      - name: Android Extra Modify 
        if: github.event.inputs.allbuild == 'true' || github.event.inputs.android == 'true'
        working-directory: sing-box-for-android
        run: |
          mkdir app/libs
          rm -rf app/release.keystore
          cp -rf ${{ github.workspace }}/.github/workflows/box.jks app/release.keystore
          sed -i 's/include("armeabi-v7a", "arm64-v8a", "x86", "x86_64")/include("arm64-v8a", "x86_64")/' app/build.gradle.kts
          echo ALIAS_NAME='${{ secrets.KEY_PASS }}' > ./local.properties
          echo KEYSTORE_PASS='${{ secrets.KEY_PASS }}' >> ./local.properties
          echo ALIAS_PASS='${{ secrets.KEY_PASS }}' >> ./local.properties

      - name: Setup Android NDK
        if: github.event.inputs.allbuild == 'true' || github.event.inputs.android == 'true'
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Setup OpenJDK
        if: github.event.inputs.allbuild == 'true' || github.event.inputs.android == 'true'
        run: |-
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
          
      # ==================== 安卓版构建与上传 ====================
      - name: Build Android
        if: github.event.inputs.allbuild == 'true' || github.event.inputs.android == 'true'
        working-directory: sing-box
        run: |-
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android
          cd ../sing-box-for-android
          git submodule update --init --recursive -v
          cd ../sing-box
          make build_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Prepare Android upload
        if: (github.event.inputs.allbuild == 'true' || github.event.inputs.android == 'true') && github.event.name == 'workflow_dispatch'
        run: |-
          mkdir -p andriod
          ls sing-box-for-android/app/build/outputs/apk/other/release/ || echo "Apk 目录不存在！"
          cp sing-box-for-android/app/build/outputs/apk/other/release/*.apk andriod/ || echo "没有找到可复制的 APK"

      - name: Upload Android artifact
        if: (github.event.inputs.allbuild == 'true' || github.event.inputs.android == 'true') && github.event.name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: SFA-arm64-v8a.apk
          path: andriod
