name: Test
on:
  workflow_dispatch:
    inputs:
      allbuild:
        description: '构建全部'
        required: false
        type: boolean
      donotpublish:
        description: '构建桌面版本'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout Source Code
        run: |
          git clone https://github.com/SagerNet/sing-box sing-box
          git clone https://github.com/SagerNet/sing-box-for-android sing-box-for-android
      - name: Android Extra Modify 
        working-directory: sing-box-for-android
        run: |
          mkdir app/libs
          git checkout dev
          rm -rf app/release.keystore
          cp -rf ${{ github.workspace }}/.github/workflows/box.jks app/release.keystore
          sed -i 's/include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"/include "arm64-v8a"/' app/build.gradle
          echo ALIAS_NAME='${{ secrets.KEY_PASS }}' > ./local.properties
          echo KEYSTORE_PASS='${{ secrets.KEY_PASS }}' >> ./local.properties
          echo ALIAS_PASS='${{ secrets.KEY_PASS }}' >> ./local.properties
          
      - name: sing-box Extra Modify
        run: |
          echo '修改VersionName'
          openssl des3 -md sha256 -d -k ${{ secrets.TAR_PASS }} -salt -in extra.tar.gz | tar -xzvf -
          sh modify.sh
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.1
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28
      - name: Setup OpenJDK
        run: |-
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
      - name: Build Desktop
        working-directory: sing-box
        run: |-
          go mod tidy
          #make
          go build ./cmd/sing-box
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box.exe
          path: sing-box/sing-box.exe
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_aarch64
          path: sing-box/sing-box_aarch64
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_x86_64
          path: sing-box/sing-box_x86_64
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_freebsd_x86_64
          path: sing-box/sing-box_freebsdx86_64
      - name: Build Andriod
        working-directory: sing-box
        run: |-
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android_debug
          ls ../sing-box-for-android/app/libs -alh
          make build_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Prepare upload
        if: github.event_name == 'workflow_dispatch'
        run: |-
          mkdir -p andriod
          # cp sing-box/sing-box sing-box
          cp sing-box-for-android/app/build/outputs/apk/other/release/SFA-*-foss-arm64-v8a.apk andriod/SFA-foss-arm64-v8a.apk
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: SFA-arm64-v8a.apk
          path: andriod/SFA-foss-arm64-v8a.apk
