name: Test
on:
  workflow_dispatch:
    inputs:
      allbuild:
        description: '构建全部'
        required: false
        type: boolean
      donotpublish:
        description: '构建桌面版本'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout Source Code
        run: |
          git clone https://github.com/SagerNet/sing-box sing-box
          git clone https://github.com/SagerNet/sing-box-for-android sing-box-for-android
      - name: Android Extra Modify 
        working-directory: sing-box-for-android
        run: |
          mkdir app/libs
          git checkout dev
          rm -rf app/release.keystore
          cp -rf ${{ github.workspace }}/.github/workflows/box.jks app/release.keystore
          sed -i 's/include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"/include "arm64-v8a"/' app/build.gradle
          echo ALIAS_NAME='${{ secrets.KEY_PASS }}' > ./local.properties
          echo KEYSTORE_PASS='${{ secrets.KEY_PASS }}' >> ./local.properties
          echo ALIAS_PASS='${{ secrets.KEY_PASS }}' >> ./local.properties
          
      - name: sing-box Extra Modify
        run: |
          echo '修改VersionName'
          openssl des3 -md sha256 -d -k ${{ secrets.TAR_PASS }} -salt -in extra.tar.gz | tar -xzvf -
          sh modify.sh
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.1
      - name: Build Desktop
        working-directory: sing-box
        run: |-
          go mod tidy
          #make
          ls ../sing-cloak
          go build ./cmd/sing-box
