name: Test
on:
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout Source Code
        run: |
          git clone https://github.com/SagerNet/sing-box sing-box
          git clone https://github.com/SagerNet/sing-box-for-android sing-box-for-android
      - name: Extra Modify
        working-directory: sing-box
        run: |
          echo '修改VersionName'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28
      - name: Setup OpenJDK
        run: |-
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
      - name: Build Desktop
        working-directory: sing-box
        run: |-
          make
      - name: Build Andriod
        working-directory: sing-box
        run: |-
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android_debug
          make build_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Prepare upload
        if: github.event_name == 'workflow_dispatch'
        run: |-
          mkdir -p dist/release
          cp sing-box/sing-box.* dist/release
          cp sing-box-for-android/app/build/outputs/apk/other/release/*.apk dist/release
      # - name: Upload artifact
      #   if: github.event_name == 'workflow_dispatch'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: binary-android-apks
      #     path: 'dist'
